# Generated by Django 3.2.15 on 2022-10-09 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealtime',
            options={'verbose_name_plural': 'mealtimes'},
        ),
        migrations.AlterModelOptions(
            name='preptime',
            options={'verbose_name_plural': 'preptimes'},
        ),
    ]
